### ISSUE TITLE
substract -> subtract

### ISSUE THREAD

**Issue by puckey** [reg4in/vec2#1]
Your Vec2#substract method should be called Vec2#subtract

**Comment by reg4in** [comment]
Yes, you're right :+1:
I have some spare time now and I'll fix it (it's just find + replace anyway).

Question: are you actually using this? If yes, any feature suggestions?

**Comment by reg4in** [comment]
... done

**Comment by puckey** [comment]
Thanks!

I was on the lookout for a super basic vector library and came across this one on NPM.. I will add issues if I come up with any features / changes

**Comment by reg4in** [comment]
Perfect! Thanks for the feedback!
